
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 128
#define YY_END_OF_BUFFER 129
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[394] =
    {   0,
        2,    2,  129,  127,    3,    2,    1,  127,   99,  107,
       90,   91,   97,   95,    8,   96,   98,   10,    7,    4,
      111,   94,  112,    6,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,   88,   89,  105,   92,  109,   93,    3,
        2,  118,  104,  121,  108,  102,  123,  100,  124,  101,
      103,    9,   10,  113,  119,  117,  120,  114,    5,  126,
      126,   12,  126,  126,  126,  126,  126,  126,  126,  126,
      126,   27,  126,  126,  126,  126,  126,  126,  126,  126,
      126,   41,  126,   43,   47,  126,  126,  126,  126,  126,

      126,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  106,  110,  122,    9,  116,  115,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,   38,  126,  126,   44,  126,  126,
      126,   51,  126,  126,  126,   55,  126,  126,  126,  126,
      126,  126,   62,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,   76,  126,  126,  126,  126,  126,
      126,  126,  125,  126,  126,  126,  126,  126,   13,   14,

      126,   16,   17,  126,   19,  126,  126,  126,  126,  126,
      126,  126,  126,   29,   30,  126,  126,  126,  126,  126,
      126,  126,  126,   40,  126,  126,   48,   49,  126,   52,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,   73,  126,
       75,  126,   78,  126,  126,  126,  126,  126,  126,   85,
      126,  126,  126,   15,   18,  126,   21,   22,  126,  126,
      126,  126,  126,   31,  126,  126,   34,  126,   36,   37,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,   64,  126,   66,  126,  126,  126,  126,

      126,  126,   74,  126,   79,  126,  126,  126,   83,  126,
      126,   87,  126,  126,  126,  126,  126,  126,   28,  126,
       33,  126,  126,  126,  126,  126,  126,   53,  126,  126,
       57,  126,  126,   60,  126,   63,   65,   67,  126,   69,
       70,   71,   72,   77,  126,   81,   82,  126,  126,  126,
       20,  126,   24,   25,  126,  126,   35,   39,  126,  126,
      126,  126,  126,  126,   58,  126,  126,  126,  126,   84,
      126,   11,   23,   26,   32,   42,  126,   46,  126,   54,
       56,  126,   61,  126,  126,   86,   45,   50,   59,  126,
       80,   68,    0

    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    1,    1,    1,    6,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,    1,   51,   52,   40,    1,   53,   54,   55,   56,

       57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
       67,   68,   40,   69,   70,   71,   72,   73,   74,   75,
       76,   77,   78,   79,   80,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[81] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    1,
        1,    1,    1,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    1,
        1,    1,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[395] =
    {   0,
        0,    0,  299,  769,  217,  194,  769,  153,  146,   74,
      769,  769,  145,   71,  769,   70,  143,   70,  769,  769,
       68,  142,   72,  136,    0,   60,   65,   73,   71,   80,
      107,   57,  114,   62,  133,  144,  123,   79,  150,  160,
      190,  202,   88,  769,  769,  134,  769,  115,  769,  120,
      117,  769,  769,  769,  769,  769,  769,  769,  769,  769,
      769,  100,   82,   92,  769,  769,  769,   90,  769,    0,
       79,    0,  117,   85,  142,  142,  160,  190,  182,  172,
      213,  156,  191,  193,  187,  202,  188,  212,  208,  212,
      214,    0,  211,  215,    0,  246,  226,  218,  231,  234,

      246,  233,  252,  241,  252,  263,  265,  245,  273,  260,
      251,  281,  270,  274,  272,  272,  287,  287,  303,  301,
      273,  296,  306,  298,  769,  769,  769,   89,  769,  769,
      303,  311,  312,  325,  323,  324,  329,  316,  334,  321,
      329,  332,  342,  341,  350,  349,  343,  345,  348,  358,
      346,  366,  364,  370,  368,  359,  366,  374,  369,  375,
      379,    0,  374,  382,  372,    0,  373,  393,  375,  379,
      383,  397,    0,  383,  385,  394,  392,  407,  411,  408,
      400,  402,  407,  421,    0,  429,  408,  422,  429,  438,
      425,  428,    0,  424,  441,  446,  438,  434,    0,    0,

      442,    0,    0,  446,    0,  447,  441,  441,  453,  451,
      446,  463,  461,    0,    0,  455,  468,  463,  473,  472,
      481,  470,  485,    0,  483,  476,    0,    0,  477,    0,
      494,  497,  482,  488,  503,  500,  499,  495,  494,  511,
      512,  499,  505,  512,  516,  515,  528,  529,    0,  512,
        0,  521,    0,  531,  536,  536,  526,  541,  529,    0,
      531,  548,  554,    0,    0,  551,    0,    0,  543,  558,
      550,  563,  561,    0,  565,  555,    0,  561,    0,    0,
      571,  572,  575,  560,  560,  563,  578,  573,  574,  587,
      593,  585,  586,    0,  597,    0,  600,  606,  606,  605,

      594,  607,    0,  611,    0,  618,  618,  606,    0,  623,
      618,    0,  628,  628,  613,  625,  619,  620,    0,  634,
        0,  620,  639,  639,  648,  650,  654,    0,  642,  654,
        0,  654,  643,    0,  652,    0,    0,    0,  653,    0,
        0,    0,    0,    0,  658,    0,    0,  658,  659,  654,
        0,  670,    0,    0,  674,  661,    0,    0,  662,  680,
      673,  686,  674,  685,    0,  690,  672,  689,  698,    0,
      700,    0,    0,    0,    0,    0,  701,    0,  702,    0,
        0,  707,    0,  698,  711,    0,    0,    0,    0,  713,
        0,    0,  769,   99

    } ;

static yyconst flex_int16_t yy_def[395] =
    {   0,
      393,    1,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,

      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  393,  393,  393,  393,  393,  393,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,

      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,

      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,    0,  393

    } ;

static yyconst flex_uint16_t yy_nxt[850] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,    4,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       25,   33,   25,   25,   34,   25,   35,   36,   37,   25,
       38,   39,   40,   41,   42,   43,   25,   25,   25,   44,
       45,   46,   26,   27,   28,   29,   30,   31,   32,   25,
       33,   25,   25,   34,   25,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   25,   25,   25,   47,   48,   49,
       54,   57,   59,   62,   71,   63,   64,   65,   73,   60,
       58,   67,   68,   55,   91,   62,   77,   63,   81,   96,

       70,   72,   74,   78,  128,   75,  107,   79,   82,  130,
       80,  129,   76,   71,   83,  128,   84,   73,  124,   51,
      131,   50,  133,   91,   85,   77,   86,   81,   96,   72,
       87,   74,   78,   75,  126,  107,   79,   82,   88,   80,
       76,   89,   92,   83,   90,   84,  104,  124,  131,   93,
       94,  133,   85,  125,   86,   95,   97,   69,  132,   87,
       98,   66,   61,  105,   56,   53,  106,   88,  100,  134,
       89,   92,   52,   90,  108,  104,   99,  109,   93,   94,
      110,  111,  101,   95,  135,   97,  132,  102,  103,   98,
      114,  105,  112,  127,  106,  113,   51,  100,  134,  145,

      115,  136,  137,  108,   99,  140,  109,  116,  141,  110,
      111,  101,  135,  138,  148,  102,  103,  139,   50,  114,
      112,  117,  151,  113,  118,  121,  119,  145,  115,  136,
      137,  120,  146,  122,  140,  116,  147,  141,  142,  123,
      149,  143,  138,  148,  150,  154,  139,  144,  152,  157,
      117,  151,  155,  118,  121,  119,  156,  158,  153,  120,
      146,  161,  122,  162,  147,  163,  164,  142,  123,  149,
      143,  159,  150,  165,  154,  166,  144,  152,  157,  167,
      155,  168,  160,  169,  156,  158,  153,  171,  172,  170,
      161,  162,  175,  173,  163,  164,  176,  177,  393,  178,

      159,  181,  165,  166,  179,  182,  393,  174,  167,  168,
      186,  160,  169,  193,  183,  184,  171,  172,  170,  185,
      175,  180,  173,  187,  188,  176,  177,  178,  189,  197,
      181,  191,  192,  179,  182,  174,  194,  195,  199,  186,
      196,  193,  183,  184,  190,  198,  200,  185,  201,  180,
      202,  203,  187,  188,  204,  393,  205,  189,  197,  206,
      191,  192,  207,  210,  194,  211,  195,  199,  212,  196,
      208,  209,  190,  198,  213,  200,  214,  201,  215,  202,
      203,  216,  217,  204,  205,  218,  393,  219,  206,  220,
      207,  221,  210,  222,  211,  223,  224,  212,  208,  209,

      225,  226,  227,  213,  228,  214,  229,  215,  230,  231,
      216,  217,  232,  233,  218,  219,  234,  237,  220,  235,
      221,  236,  222,  238,  223,  224,  239,  240,  241,  225,
      226,  227,  242,  228,  243,  229,  244,  230,  231,  246,
      232,  233,  248,  249,  250,  234,  237,  235,  251,  236,
      253,  247,  238,  245,  239,  240,  252,  241,  254,  255,
      242,  256,  257,  243,  258,  244,  259,  260,  246,  261,
      248,  249,  262,  250,  263,  264,  265,  251,  253,  247,
      266,  245,  267,  268,  269,  252,  270,  254,  255,  271,
      256,  257,  272,  258,  259,  273,  260,  274,  261,  275,

      277,  262,  263,  276,  264,  265,  278,  279,  281,  266,
      267,  268,  280,  269,  282,  270,  283,  271,  284,  285,
      286,  272,  287,  288,  273,  274,  289,  290,  275,  277,
      291,  276,  292,  393,  293,  278,  279,  281,  294,  295,
      280,  296,  297,  282,  283,  298,  284,  299,  285,  286,
      287,  300,  288,  301,  302,  289,  290,  303,  304,  291,
      305,  292,  293,  306,  307,  393,  308,  294,  295,  296,
      309,  297,  310,  311,  298,  312,  299,  313,  314,  315,
      300,  316,  301,  302,  317,  303,  318,  304,  319,  305,
      320,  321,  306,  307,  308,  322,  323,  324,  327,  309,

      310,  311,  328,  325,  312,  329,  313,  314,  315,  330,
      316,  326,  333,  317,  331,  318,  332,  319,  334,  320,
      321,  335,  336,  337,  322,  323,  324,  327,  338,  339,
      328,  340,  325,  329,  341,  393,  342,  343,  330,  344,
      326,  333,  331,  345,  332,  346,  348,  334,  347,  349,
      335,  336,  337,  350,  351,  393,  352,  338,  339,  353,
      340,  354,  355,  341,  342,  356,  343,  357,  344,  358,
      359,  360,  345,  361,  346,  348,  347,  362,  349,  363,
      364,  365,  350,  351,  352,  366,  367,  368,  353,  354,
      355,  369,  370,  371,  356,  357,  372,  373,  358,  359,

      360,  374,  361,  375,  376,  377,  362,  378,  363,  364,
      365,  379,  381,  366,  380,  367,  368,  382,  393,  383,
      369,  370,  371,  384,  372,  385,  373,  386,  387,  388,
      374,  375,  376,  389,  377,  390,  378,  391,  392,  393,
      379,  381,  380,  393,  393,  393,  382,  383,  393,  393,
      393,  393,  384,  393,  385,  393,  386,  387,  388,  393,
      393,  393,  389,  393,  390,  393,  391,  392,    3,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,

      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393
    } ;

static yyconst flex_int16_t yy_chk[850] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       10,   14,   16,   18,   26,   18,   21,   21,   27,   16,
       14,   23,   23,   10,   32,   63,   28,   63,   29,   34,

      394,   26,   27,   28,  128,   27,   38,   28,   29,   68,
       28,   64,   27,   26,   30,   62,   30,   27,   43,   51,
       71,   50,   74,   32,   30,   28,   30,   29,   34,   26,
       31,   27,   28,   27,   48,   38,   28,   29,   31,   28,
       27,   31,   33,   30,   31,   30,   37,   43,   71,   33,
       33,   74,   30,   46,   30,   33,   35,   24,   73,   31,
       35,   22,   17,   37,   13,    9,   37,   31,   36,   75,
       31,   33,    8,   31,   39,   37,   35,   39,   33,   33,
       39,   39,   36,   33,   76,   35,   73,   36,   36,   35,
       40,   37,   39,   48,   37,   39,    6,   36,   75,   82,

       40,   77,   77,   39,   35,   79,   39,   40,   80,   39,
       39,   36,   76,   78,   85,   36,   36,   78,    5,   40,
       39,   41,   87,   39,   41,   42,   41,   82,   40,   77,
       77,   41,   83,   42,   79,   40,   84,   80,   81,   42,
       86,   81,   78,   85,   86,   89,   78,   81,   88,   93,
       41,   87,   90,   41,   42,   41,   91,   94,   88,   41,
       83,   97,   42,   98,   84,   99,  100,   81,   42,   86,
       81,   96,   86,  101,   89,  102,   81,   88,   93,  103,
       90,  104,   96,  105,   91,   94,   88,  106,  107,  105,
       97,   98,  108,  107,   99,  100,  109,  110,    3,  111,

       96,  113,  101,  102,  112,  114,    0,  107,  103,  104,
      116,   96,  105,  121,  114,  115,  106,  107,  105,  115,
      108,  112,  107,  117,  118,  109,  110,  111,  119,  124,
      113,  120,  120,  112,  114,  107,  122,  123,  132,  116,
      123,  121,  114,  115,  119,  131,  133,  115,  134,  112,
      135,  136,  117,  118,  137,    0,  138,  119,  124,  139,
      120,  120,  140,  142,  122,  143,  123,  132,  144,  123,
      141,  141,  119,  131,  145,  133,  146,  134,  147,  135,
      136,  148,  149,  137,  138,  150,    0,  151,  139,  152,
      140,  153,  142,  154,  143,  155,  156,  144,  141,  141,

      157,  158,  159,  145,  160,  146,  161,  147,  163,  164,
      148,  149,  165,  167,  150,  151,  168,  171,  152,  169,
      153,  170,  154,  172,  155,  156,  174,  175,  176,  157,
      158,  159,  177,  160,  178,  161,  179,  163,  164,  180,
      165,  167,  181,  182,  183,  168,  171,  169,  184,  170,
      187,  180,  172,  179,  174,  175,  186,  176,  188,  189,
      177,  190,  191,  178,  192,  179,  194,  195,  180,  196,
      181,  182,  197,  183,  198,  201,  204,  184,  187,  180,
      206,  179,  207,  208,  209,  186,  210,  188,  189,  211,
      190,  191,  212,  192,  194,  213,  195,  216,  196,  217,

      219,  197,  198,  218,  201,  204,  220,  221,  223,  206,
      207,  208,  222,  209,  225,  210,  226,  211,  229,  231,
      232,  212,  233,  234,  213,  216,  235,  236,  217,  219,
      237,  218,  238,    0,  239,  220,  221,  223,  240,  241,
      222,  242,  243,  225,  226,  244,  229,  245,  231,  232,
      233,  246,  234,  247,  248,  235,  236,  250,  252,  237,
      254,  238,  239,  255,  256,    0,  257,  240,  241,  242,
      258,  243,  259,  261,  244,  262,  245,  263,  266,  269,
      246,  270,  247,  248,  271,  250,  272,  252,  273,  254,
      275,  276,  255,  256,  257,  278,  281,  282,  284,  258,

      259,  261,  285,  283,  262,  286,  263,  266,  269,  287,
      270,  283,  290,  271,  288,  272,  289,  273,  291,  275,
      276,  292,  293,  295,  278,  281,  282,  284,  297,  298,
      285,  299,  283,  286,  300,    0,  301,  302,  287,  304,
      283,  290,  288,  306,  289,  307,  310,  291,  308,  311,
      292,  293,  295,  313,  314,    0,  315,  297,  298,  316,
      299,  317,  318,  300,  301,  320,  302,  322,  304,  323,
      324,  325,  306,  326,  307,  310,  308,  327,  311,  329,
      330,  332,  313,  314,  315,  333,  335,  339,  316,  317,
      318,  345,  348,  349,  320,  322,  350,  352,  323,  324,

      325,  355,  326,  356,  359,  360,  327,  361,  329,  330,
      332,  362,  364,  333,  363,  335,  339,  366,    0,  367,
      345,  348,  349,  368,  350,  369,  352,  371,  377,  379,
      355,  356,  359,  382,  360,  384,  361,  385,  390,    0,
      362,  364,  363,    0,    0,    0,  366,  367,    0,    0,
        0,    0,  368,    0,  369,    0,  371,  377,  379,    0,
        0,    0,  382,    0,  384,    0,  385,  390,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,

      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[129] =
    {   0,
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "analyseur_csharp.l"
#line 2 "analyseur_csharp.l"
#include <stdio.h>
#include "analyseur_csharp.h"
	boolean debug=true;
#line 822 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state (int _new_state );
    
    static void yy_pop_state (void );
    
    static int yy_top_state (void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 17 "analyseur_csharp.l"

#line 1052 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 394 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 769 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 18 "analyseur_csharp.l"
{}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 19 "analyseur_csharp.l"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 20 "analyseur_csharp.l"
{}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 21 "analyseur_csharp.l"
{if (debug) printf ("; \n"); return PVIRG;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 22 "analyseur_csharp.l"
{if (debug) printf ("?? \n");return NULLCOALESCING;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 23 "analyseur_csharp.l"
{if (debug) printf ("? \n");return POINTINTER;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 24 "analyseur_csharp.l"
{if (debug) printf (": \n");return DOUBLEDOT;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 25 "analyseur_csharp.l"
{if (debug) printf (", \n");return VIRG;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 26 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return DOUBLENUMBER;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 27 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return INTNUMBER;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 28 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return ABSTRACT;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 29 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return AS;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 30 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return BASE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 31 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return BOOL;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 32 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return BREAK;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 33 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return BYTE;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 34 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return CASE;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 35 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return CATCH;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 36 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return CHAR;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 37 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return CHECKED;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 38 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return CLASS;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 39 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return CONST;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 40 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return CONTINUE;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 41 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return DECIMAL;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 42 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return DEFAULT;}	
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 43 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return DELEGATE;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 44 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return DO;}	
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 45 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return DOUBLE;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 46 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return ELSE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 47 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return ENUM;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 48 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return EVENT;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 49 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return EXPLICIT;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 50 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return EXTERN;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 51 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return FALSE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 52 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return FINALLY;} 	
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 53 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return FIXED;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 54 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return FLOAT;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 55 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return FOR;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 56 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return FOREACH;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 57 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return GOTO;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 58 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return IF;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 59 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return IMPLICIT;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 60 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return IN;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 61 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return INT;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 62 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return INTERFACE;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 63 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return INTERNAL;}	
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 64 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return IS;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 65 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return LOCK;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 66 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return LONG;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 67 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return NAMESPACE;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 68 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return NEW;} 		
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 69 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return NNULL;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 70 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return OBJECT;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 71 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return OPERATOR;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 72 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return OUT;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 73 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return OVERRIDE;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 74 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return PARAMS;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 75 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return PRIVATE;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 76 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return PROTECTED;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 77 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return PUBLIC;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 78 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return READONLY;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 79 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return REF;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 80 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return RETURN;}	
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 81 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return SBYTE;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 82 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return SEALED;}	
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 83 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return SHORT;}	
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 84 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return SIZEOF;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 85 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return STACKALLOC;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 86 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return STATIC;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 87 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return STRING;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 88 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return STRUCT;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 89 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return SWITCH;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 90 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return THIS;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 91 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return THROW;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 92 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return TRUE;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 93 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return TRY;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 94 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return TYPEOF;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 95 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return UINT;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 96 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return ULONG;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 97 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return UNCHECKED;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 98 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return UNSAFE;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 99 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return USHORT;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 100 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return USING;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 101 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return VIRTUAL;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 102 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return VOID;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 103 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return VOLATILE;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 104 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return WHILE;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 105 "analyseur_csharp.l"
{if (debug) printf ("[ \n"); return LEFTBRACKET;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 106 "analyseur_csharp.l"
{if (debug) printf ("] \n"); return RIGHTBRACKET;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 107 "analyseur_csharp.l"
{if (debug) printf ("( \n"); return POPEN;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 108 "analyseur_csharp.l"
{if (debug) printf (") \n"); return PCLOSE;}		
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 109 "analyseur_csharp.l"
{if (debug) printf ("{ \n"); return BOPEN;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 110 "analyseur_csharp.l"
{if (debug) printf ("} \n"); return BCLOSE;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 111 "analyseur_csharp.l"
{if (debug) printf ("= \n"); return EQ;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 112 "analyseur_csharp.l"
{if (debug) printf ("+ \n"); return PLUS;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 113 "analyseur_csharp.l"
{if (debug) printf ("- \n"); return MINUS;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 114 "analyseur_csharp.l"
{if (debug) printf ("* \n"); return MULT;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 115 "analyseur_csharp.l"
{if (debug) printf ("/ \n"); return DIV;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 116 "analyseur_csharp.l"
{if (debug) printf ("/ \n"); return MOD;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 117 "analyseur_csharp.l"
{if (debug) printf ("+= \n"); return PLUSEQ; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 118 "analyseur_csharp.l"
{if (debug) printf ("-= \n"); return MINUSEQ; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 119 "analyseur_csharp.l"
{if (debug) printf ("*= \n"); return STAREQ; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 120 "analyseur_csharp.l"
{if (debug) printf ("/= \n"); return DIVEQ; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 121 "analyseur_csharp.l"
{if (debug) printf ("MODEQ \n"); return MODEQ; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 122 "analyseur_csharp.l"
{if (debug) printf ("^ \n"); return XOR; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 123 "analyseur_csharp.l"
{if (debug) printf ("^= \n"); return XOREQ; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 124 "analyseur_csharp.l"
{if (debug) printf ("& \n"); return AND; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 125 "analyseur_csharp.l"
{if (debug) printf ("&= \n"); return ANDEQ; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 126 "analyseur_csharp.l"
{if (debug) printf ("| \n"); return OR; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 127 "analyseur_csharp.l"
{if (debug) printf ("|= \n"); return OREQ; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 128 "analyseur_csharp.l"
{if (debug) printf ("< \n"); return LT; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 129 "analyseur_csharp.l"
{if (debug) printf ("> \n"); return GT; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 130 "analyseur_csharp.l"
{if (debug) printf ("<< \n"); return LTLT; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 131 "analyseur_csharp.l"
{if (debug) printf (">> \n"); return GTGT; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 132 "analyseur_csharp.l"
{if (debug) printf (">>= \n"); return GTGTEQ; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 133 "analyseur_csharp.l"
{if (debug) printf ("<<= \n"); return LTLTEQ; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 134 "analyseur_csharp.l"
{if (debug) printf ("== \n"); return EQEQ; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 135 "analyseur_csharp.l"
{if (debug) printf ("!= \n"); return NOTEQ; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 136 "analyseur_csharp.l"
{if (debug) printf ("<= \n"); return LEQ; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 137 "analyseur_csharp.l"
{if (debug) printf (">= \n"); return GEQ; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 138 "analyseur_csharp.l"
{if (debug) printf ("&& \n"); return ANDAND; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 139 "analyseur_csharp.l"
{if (debug) printf ("|| \n"); return OROR; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 140 "analyseur_csharp.l"
{if (debug) printf ("++ \n"); return PLUSPLUS; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 141 "analyseur_csharp.l"
{if (debug) printf ("-- \n"); return MINUSMINUS; }	
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 142 "analyseur_csharp.l"
{if (debug) printf ("VAR \n"); return VAR;}		
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 143 "analyseur_csharp.l"
{if (debug) printf ("EOF \n"); return END_OF_FILE;}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 144 "analyseur_csharp.l"
{if (debug) printf ("identifier \n");	return IDF;}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 145 "analyseur_csharp.l"
{ printf( "ERRORLEX(%s) ", yytext );}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 147 "analyseur_csharp.l"
ECHO;
	YY_BREAK
#line 1764 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 394 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 394 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 393);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc(new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        yyfree((yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 147 "analyseur_csharp.l"



