
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 134
#define YY_END_OF_BUFFER 135
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[410] =
    {   0,
        2,    2,  135,  133,    3,    2,    1,  114,  103,  111,
       94,   95,  101,   99,    9,  100,    8,  102,   11,    7,
        4,  117,   98,  118,    6,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,   92,   93,  109,   96,  115,   97,
      113,    3,    2,  124,  108,  127,  112,  106,  129,  104,
      130,  105,  107,   10,   11,  119,  125,  123,  126,  120,
        5,  132,  132,   13,  132,  132,  132,  132,  132,  132,
      132,  132,  132,   28,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,   42,  132,   44,   48,  132,  132,

      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  110,  116,  128,
       10,  122,  121,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,   39,  132,
      132,   45,  132,  132,  132,   52,  132,  132,  132,   57,
      132,  132,  132,  132,  132,  132,   64,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,   78,
      132,  132,  132,  132,  132,  132,  132,  131,  132,  132,

      132,  132,  132,   14,   15,  132,   17,   18,  132,   20,
      132,  132,  132,  132,  132,  132,  132,  132,  132,   30,
       31,  132,  132,  132,  132,  132,  132,  132,  132,   41,
      132,  132,   49,   50,  132,   53,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,   75,  132,   77,  132,
       80,  132,  132,  132,  132,  132,  132,   87,  132,  132,
      132,   16,   19,  132,   22,   23,  132,  132,  132,  132,
      132,  132,   32,  132,  132,   35,  132,   37,   38,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,

      132,  132,  132,  132,   66,  132,   68,  132,  132,  132,
      132,  132,  132,   76,  132,   81,  132,  132,  132,   85,
      132,  132,   89,  132,  132,  132,  132,  132,  132,   29,
      132,  132,   34,  132,  132,  132,  132,  132,  132,   54,
      132,  132,   59,  132,  132,  132,   62,  132,   90,   65,
       67,   69,  132,   71,   72,   73,   74,   79,  132,   83,
       84,  132,  132,  132,   21,  132,   25,   26,  132,   55,
      132,   36,   40,  132,  132,  132,  132,  132,  132,   91,
       60,  132,  132,  132,  132,   86,  132,   12,   24,   27,
       33,   43,  132,   47,  132,   56,   58,  132,   63,  132,

      132,   88,   46,   51,   61,  132,   82,   70,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    1,    1,    1,    6,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,    1,   51,   52,   40,    1,   53,   54,   55,   56,

       57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
       67,   68,   40,   69,   70,   71,   72,   73,   74,   75,
       76,   77,   78,   79,   80,   81,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[82] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    1,
        1,    1,    1,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    1,
        1,    1,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    1,    1,    1,
        1
    } ;

static yyconst flex_uint16_t yy_base[411] =
    {   0,
        0,    0,  761,  787,  758,  471,  787,  431,  288,   75,
      787,  787,  258,   72,  787,   71,  787,  189,   71,  787,
      787,   69,  178,   73,  149,    0,   61,   66,   74,   72,
       81,  108,   58,  115,   63,  134,  145,  135,   80,  169,
      162,  200,  195,   90,  787,  787,  146,  787,   86,  787,
      787,  158,  120,  787,  787,  787,  787,  787,  787,  787,
      787,  787,  787,  106,   83,   97,  787,  787,  787,   93,
      787,    0,   94,    0,  107,   86,  135,  112,  125,  192,
      158,  168,  218,  130,  184,  144,  164,  197,  212,  193,
      221,  208,  183,  196,    0,  220,  198,    0,  234,  227,

      219,  237,  241,  249,  236,  253,  243,  253,  261,  266,
      246,  273,  260,  255,  275,  273,  289,  269,  272,  281,
      285,  307,  304,  284,  288,  307,  306,  787,  787,  787,
       95,  787,  787,  303,  315,  316,  330,  327,  328,  333,
      307,  334,  321,  327,  329,  342,  345,  350,  354,  351,
      345,  345,  351,  359,  350,  369,  366,  372,  371,  362,
      366,  375,  371,  376,  381,    0,  377,  385,  376,    0,
      377,  390,  374,  378,  389,  399,    0,  389,  387,  393,
      402,  398,  412,  422,  418,  401,  410,  416,  429,    0,
      430,  417,  426,  437,  446,  433,  436,    0,  432,  449,

      454,  446,  443,    0,    0,  448,    0,    0,  454,    0,
      455,  449,  451,  463,  460,  454,  471,  469,  470,    0,
        0,  465,  477,  472,  487,  481,  490,  477,  497,    0,
      491,  486,    0,    0,  486,    0,  503,  507,  493,  496,
      505,  515,  512,  510,  505,  502,  508,  523,  525,  514,
      516,  525,  531,  527,  539,  541,    0,  524,    0,  535,
        0,  544,  548,  549,  540,  549,  540,    0,  543,  559,
      565,    0,    0,  562,    0,    0,  554,  571,  562,  575,
      572,  569,    0,  578,  569,    0,  575,    0,    0,  585,
      587,  586,  578,  578,  579,  593,  585,  607,  591,  606,

      610,  600,  610,  604,    0,  616,    0,  616,  623,  622,
      621,  610,  625,    0,  628,    0,  632,  631,  620,    0,
      640,  636,    0,  643,  644,  629,  640,  635,  636,    0,
      656,  651,    0,  641,  653,  658,  668,  670,  671,    0,
      658,  672,    0,  667,  675,  662,    0,  673,    0,    0,
        0,    0,  674,    0,    0,    0,    0,    0,  676,    0,
        0,  679,  680,  675,    0,  688,    0,    0,  692,    0,
      679,    0,    0,  683,  701,  694,  704,  693,  707,    0,
        0,  708,  692,  706,  714,    0,  719,    0,    0,    0,
        0,    0,  720,    0,  723,    0,    0,  725,    0,  715,

      728,    0,    0,    0,    0,  731,    0,    0,  787,  100
    } ;

static yyconst flex_int16_t yy_def[411] =
    {   0,
      409,    1,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,

      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  409,  409,  409,
      409,  409,  409,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,

      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,

      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,

      410,  410,  410,  410,  410,  410,  410,  410,    0,  409
    } ;

static yyconst flex_uint16_t yy_nxt[869] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       26,   34,   26,   26,   35,   26,   36,   37,   38,   26,
       39,   40,   41,   42,   43,   44,   26,   26,   26,   45,
       46,   47,   27,   28,   29,   30,   31,   32,   33,   26,
       34,   26,   26,   35,   26,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   26,   26,   26,   48,   49,   50,
       51,   56,   59,   61,   64,   73,   65,   66,   67,   75,
       62,   60,   69,   70,   57,   94,   64,   79,   65,   83,

       99,   72,   74,   76,   80,  129,   77,  110,   81,   84,
      131,   82,  133,   78,   73,   86,  132,   87,   75,   85,
      127,  131,   53,  136,   94,   88,   79,   89,   83,   99,
       74,   90,   76,   80,   77,  134,  110,   81,   84,   91,
       82,   78,   92,   95,   86,   93,   87,   85,  135,  127,
       96,   97,  136,   88,  138,   89,   98,  100,  107,   52,
       90,  101,  137,  134,  130,  128,  139,  140,   91,  103,
       71,   92,   95,  148,   93,  108,  135,  102,  109,   96,
       97,  143,  138,  104,   98,  150,  100,  107,  105,  106,
      101,  137,  117,  111,  139,  140,  112,   68,  103,  113,

      114,  148,  118,  108,  144,  102,  109,  151,   63,  119,
      143,  115,  104,  150,  116,  141,  105,  106,  124,  142,
      149,  117,  111,  159,  152,  112,  125,  155,  113,  114,
      118,  120,  126,  144,  121,  151,  122,  119,  160,  115,
      162,  123,  116,  145,  141,  158,  146,  124,  142,  149,
      153,  159,  147,  152,  154,  125,  155,  156,  161,  163,
      120,  126,  165,  121,  166,  122,  160,  157,  162,  123,
      164,  167,  145,  168,  158,  146,  169,   58,  170,  153,
      171,  147,  154,  172,  173,  175,  156,  161,  163,  176,
      174,  165,  166,  180,  177,  157,  181,  182,  184,  164,

      167,  178,  168,  183,  186,  169,  170,   55,  179,  171,
      191,  172,  189,  173,  175,  185,  190,  192,  176,  174,
      187,  180,  193,  177,  198,  181,  182,  184,  199,  188,
      178,  183,  194,  186,  196,  197,  179,  202,  200,  191,
      189,  201,  204,  185,  190,  203,  192,  210,  195,  187,
      205,  193,  198,  206,  207,  208,  199,  188,  209,  211,
      215,  194,  212,  196,  197,  216,  202,  200,  213,  214,
      201,  204,  217,  203,  218,  210,  195,  219,  220,  205,
      221,  222,  206,  207,  208,  223,  224,  209,  211,  215,
      212,  225,  226,  227,  216,  228,  213,  214,  229,  230,

      231,  217,  232,  218,  233,  234,  219,  220,  235,  221,
      222,  236,  237,  240,  223,  224,  238,  239,  242,  225,
      243,  226,  227,  244,  228,  245,  246,  229,  230,  231,
      247,  232,  241,  233,  234,  248,  249,  235,  250,  251,
      236,  237,  240,  256,  238,  239,  242,  252,  243,  254,
       54,  257,  244,  258,  245,  246,  259,  260,  247,  261,
      241,  255,  262,  248,  253,  249,  250,  263,  251,  264,
      265,  256,  266,   53,  267,  268,  252,  269,  254,  257,
      270,  272,  258,  271,  273,  259,  260,  261,  274,  255,
      275,  262,  253,  276,  277,  278,  263,  279,  264,  265,

      280,  266,  267,  281,  268,  282,  269,  283,  284,  270,
      272,  271,  285,  273,  286,  287,  288,  274,  275,  289,
      290,  276,  291,  277,  278,  279,  292,  293,  294,  280,
      295,  297,  281,  296,  282,  283,  298,  284,  299,  300,
      285,  301,  302,  286,  287,  288,  303,  289,  304,  290,
      305,  291,  306,  308,  292,  293,  307,  294,  309,  295,
      297,  296,  310,  311,  312,  298,  313,  299,  300,  314,
      301,  302,  315,  316,  303,  317,  304,  318,  320,  305,
      319,  306,  308,  321,  307,  322,  323,  309,  324,  325,
      326,  310,  311,  312,  327,  313,  328,  314,  329,  330,

      331,  315,  316,  332,  317,  333,  318,  320,  319,  334,
      335,  321,  336,  322,  337,  323,  339,  324,  325,  326,
      340,  341,  338,  327,  342,  328,  343,  329,  330,  331,
      344,  346,  332,  345,  333,  347,  348,  349,  334,  335,
      350,  336,  351,  337,  352,  339,  353,  354,  340,  341,
      355,  338,  356,  342,  343,  357,  358,  359,  360,  344,
      346,  345,  361,  362,  347,  348,  349,  363,  364,  350,
      365,  351,  366,  352,  367,  353,  354,  368,  369,  355,
      356,  370,  371,  373,  357,  358,  359,  360,  372,  374,
      361,  375,  362,  376,  377,  378,  363,  364,  379,  365,

      366,  380,  381,  367,  382,  368,  369,  383,  384,  385,
      370,  371,  373,  386,  387,  389,  372,  388,  374,  390,
      375,  391,  376,  377,  378,  392,  393,  379,  394,  395,
      380,  381,  382,  396,  397,  398,  383,  384,  385,  399,
      400,  401,  386,  387,  389,  388,  402,  403,  390,  391,
      404,  405,  406,  392,  407,  393,  408,  394,  395,   52,
      409,  396,  409,  397,  398,  409,  409,  399,  409,  400,
      401,  409,  409,  409,  409,  402,  403,  409,  409,  404,
      405,  406,  409,  407,  409,  408,    3,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,

      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409
    } ;

static yyconst flex_int16_t yy_chk[869] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   10,   14,   16,   19,   27,   19,   22,   22,   28,
       16,   14,   24,   24,   10,   33,   65,   29,   65,   30,

       35,  410,   27,   28,   29,   49,   28,   39,   29,   30,
      131,   29,   70,   28,   27,   31,   66,   31,   28,   30,
       44,   64,   53,   76,   33,   31,   29,   31,   30,   35,
       27,   32,   28,   29,   28,   73,   39,   29,   30,   32,
       29,   28,   32,   34,   31,   32,   31,   30,   75,   44,
       34,   34,   76,   31,   78,   31,   34,   36,   38,   52,
       32,   36,   77,   73,   49,   47,   79,   79,   32,   37,
       25,   32,   34,   84,   32,   38,   75,   36,   38,   34,
       34,   81,   78,   37,   34,   86,   36,   38,   37,   37,
       36,   77,   41,   40,   79,   79,   40,   23,   37,   40,

       40,   84,   41,   38,   82,   36,   38,   87,   18,   41,
       81,   40,   37,   86,   40,   80,   37,   37,   43,   80,
       85,   41,   40,   93,   88,   40,   43,   90,   40,   40,
       41,   42,   43,   82,   42,   87,   42,   41,   94,   40,
       97,   42,   40,   83,   80,   92,   83,   43,   80,   85,
       89,   93,   83,   88,   89,   43,   90,   91,   96,   99,
       42,   43,  100,   42,  101,   42,   94,   91,   97,   42,
       99,  102,   83,  103,   92,   83,  104,   13,  105,   89,
      106,   83,   89,  107,  108,  109,   91,   96,   99,  110,
      108,  100,  101,  111,  110,   91,  112,  113,  115,   99,

      102,  110,  103,  114,  116,  104,  105,    9,  110,  106,
      119,  107,  118,  108,  109,  115,  118,  120,  110,  108,
      117,  111,  121,  110,  124,  112,  113,  115,  125,  117,
      110,  114,  122,  116,  123,  123,  110,  127,  126,  119,
      118,  126,  135,  115,  118,  134,  120,  141,  122,  117,
      136,  121,  124,  137,  138,  139,  125,  117,  140,  142,
      145,  122,  143,  123,  123,  146,  127,  126,  144,  144,
      126,  135,  147,  134,  148,  141,  122,  149,  150,  136,
      151,  152,  137,  138,  139,  153,  154,  140,  142,  145,
      143,  155,  156,  157,  146,  158,  144,  144,  159,  160,

      161,  147,  162,  148,  163,  164,  149,  150,  165,  151,
      152,  167,  168,  172,  153,  154,  169,  171,  173,  155,
      174,  156,  157,  175,  158,  176,  178,  159,  160,  161,
      179,  162,  172,  163,  164,  180,  181,  165,  182,  183,
      167,  168,  172,  186,  169,  171,  173,  184,  174,  185,
        8,  187,  175,  188,  176,  178,  189,  191,  179,  192,
      172,  185,  193,  180,  184,  181,  182,  194,  183,  195,
      196,  186,  197,    6,  199,  200,  184,  201,  185,  187,
      202,  206,  188,  203,  209,  189,  191,  192,  211,  185,
      212,  193,  184,  213,  214,  215,  194,  216,  195,  196,

      217,  197,  199,  218,  200,  219,  201,  222,  223,  202,
      206,  203,  224,  209,  225,  226,  227,  211,  212,  228,
      229,  213,  231,  214,  215,  216,  232,  235,  237,  217,
      238,  240,  218,  239,  219,  222,  241,  223,  242,  243,
      224,  244,  245,  225,  226,  227,  246,  228,  247,  229,
      248,  231,  249,  251,  232,  235,  250,  237,  252,  238,
      240,  239,  253,  254,  255,  241,  256,  242,  243,  258,
      244,  245,  260,  262,  246,  263,  247,  264,  266,  248,
      265,  249,  251,  267,  250,  269,  270,  252,  271,  274,
      277,  253,  254,  255,  278,  256,  279,  258,  280,  281,

      282,  260,  262,  284,  263,  285,  264,  266,  265,  287,
      290,  267,  291,  269,  292,  270,  293,  271,  274,  277,
      294,  295,  292,  278,  296,  279,  297,  280,  281,  282,
      298,  300,  284,  299,  285,  301,  302,  303,  287,  290,
      304,  291,  306,  292,  308,  293,  309,  310,  294,  295,
      311,  292,  312,  296,  297,  313,  315,  317,  318,  298,
      300,  299,  319,  321,  301,  302,  303,  322,  324,  304,
      325,  306,  326,  308,  327,  309,  310,  328,  329,  311,
      312,  331,  332,  335,  313,  315,  317,  318,  334,  336,
      319,  337,  321,  338,  339,  341,  322,  324,  342,  325,

      326,  344,  345,  327,  346,  328,  329,  348,  353,  359,
      331,  332,  335,  362,  363,  366,  334,  364,  336,  369,
      337,  371,  338,  339,  341,  374,  375,  342,  376,  377,
      344,  345,  346,  378,  379,  382,  348,  353,  359,  383,
      384,  385,  362,  363,  366,  364,  387,  393,  369,  371,
      395,  398,  400,  374,  401,  375,  406,  376,  377,    5,
        3,  378,    0,  379,  382,    0,    0,  383,    0,  384,
      385,    0,    0,    0,    0,  387,  393,    0,    0,  395,
      398,  400,    0,  401,    0,  406,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,

      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[135] =
    {   0,
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "analyseur_csharp.l"
#line 2 "analyseur_csharp.l"
#include <stdio.h>
#include "analyseur_csharp.h"
	boolean debug=true;
#line 830 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state (int _new_state );
    
    static void yy_pop_state (void );
    
    static int yy_top_state (void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 17 "analyseur_csharp.l"

#line 1060 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 410 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 787 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 18 "analyseur_csharp.l"
{}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 19 "analyseur_csharp.l"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 20 "analyseur_csharp.l"
{}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 21 "analyseur_csharp.l"
{if (debug) printf ("; \n"); return PVIRG;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 22 "analyseur_csharp.l"
{if (debug) printf ("?? \n");return NULLCOALESCING;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 23 "analyseur_csharp.l"
{if (debug) printf ("? \n");return POINTINTER;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 24 "analyseur_csharp.l"
{if (debug) printf (": \n");return DOUBLEDOT;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 25 "analyseur_csharp.l"
{if (debug) printf (". \n");return POINT;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 26 "analyseur_csharp.l"
{if (debug) printf (", \n");return VIRG;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 27 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext); set_number_attributes(atof(yytext));	return DOUBLENUMBER;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 28 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext); set_number_attributes((double)atoi(yytext));	return INTNUMBER;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 29 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return ABSTRACT;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 30 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return AS;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 31 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return BASE;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 32 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return BOOL;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 33 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return BREAK;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 34 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return BYTE;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 35 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return CASE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 36 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return CATCH;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 37 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return CHAR;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 38 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return CHECKED;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 39 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return CLASS;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 40 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return CONST;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 41 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return CONTINUE;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 42 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return DECIMAL;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 43 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return DEFAULT;}	
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 44 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return DELEGATE;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 45 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return DO;}	
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 46 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return DOUBLE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 47 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return ELSE;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 48 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return ENUM;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 49 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return EVENT;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 50 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return EXPLICIT;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 51 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return EXTERN;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 52 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return FALSE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 53 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return FINALLY;} 	
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 54 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return FIXED;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 55 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return FLOAT;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 56 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return FOR;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 57 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return FOREACH;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 58 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return GOTO;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 59 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return IF;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 60 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return IMPLICIT;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 61 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return IN;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 62 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return INT;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 63 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return INTERFACE;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 64 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return INTERNAL;}	
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 65 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return IS;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 66 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return LOCK;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 67 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return LONG;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 68 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return NAMESPACE;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 69 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return NEW;} 		
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 70 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return NNULL;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 71 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return OBJECT;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 72 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return DYNAMIC;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 73 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return OPERATOR;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 74 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return OUT;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 75 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return OVERRIDE;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 76 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return PARAMS;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 77 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return PRIVATE;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 78 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return PROTECTED;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 79 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return PUBLIC;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 80 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return READONLY;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 81 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return REF;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 82 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return RETURN;}	
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 83 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return SBYTE;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 84 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return SEALED;}	
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 85 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return SHORT;}	
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 86 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return SIZEOF;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 87 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return STACKALLOC;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 88 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return STATIC;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 89 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return STRING;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 90 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return STRUCT;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 91 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return SWITCH;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 92 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return THIS;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 93 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return THROW;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 94 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return TRUE;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 95 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return TRY;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 96 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return TYPEOF;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 97 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return UINT;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 98 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return ULONG;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 99 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return UNCHECKED;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 100 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return UNSAFE;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 101 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return USHORT;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 102 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return USING;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 103 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return VIRTUAL;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 104 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return VOID;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 105 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return VOLATILE;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 106 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return WHILE;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 107 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return REMOVE;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 108 "analyseur_csharp.l"
{if (debug) printf ("%s \n",yytext);	return PARTIAL;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 109 "analyseur_csharp.l"
{if (debug) printf ("[ \n"); return LEFTBRACKET;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 110 "analyseur_csharp.l"
{if (debug) printf ("] \n"); return RIGHTBRACKET;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 111 "analyseur_csharp.l"
{if (debug) printf ("( \n"); return POPEN;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 112 "analyseur_csharp.l"
{if (debug) printf (") \n"); return PCLOSE;}		
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 113 "analyseur_csharp.l"
{if (debug) printf ("{ \n"); return BOPEN;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 114 "analyseur_csharp.l"
{if (debug) printf ("} \n"); return BCLOSE;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 115 "analyseur_csharp.l"
{if (debug) printf ("= \n"); return EQ;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 116 "analyseur_csharp.l"
{if (debug) printf ("+ \n"); return PLUS;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 117 "analyseur_csharp.l"
{if (debug) printf ("- \n"); return MINUS;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 118 "analyseur_csharp.l"
{if (debug) printf ("* \n"); return MULT;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 119 "analyseur_csharp.l"
{if (debug) printf ("/ \n"); return DIV;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 120 "analyseur_csharp.l"
{if (debug) printf ("/ \n"); return MOD;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 121 "analyseur_csharp.l"
{if (debug) printf ("+= \n"); return PLUSEQ; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 122 "analyseur_csharp.l"
{if (debug) printf ("-= \n"); return MINUSEQ; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 123 "analyseur_csharp.l"
{if (debug) printf ("*= \n"); return STAREQ; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 124 "analyseur_csharp.l"
{if (debug) printf ("/= \n"); return DIVEQ; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 125 "analyseur_csharp.l"
{if (debug) printf ("MODEQ \n"); return MODEQ; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 126 "analyseur_csharp.l"
{if (debug) printf ("^ \n"); return XOR; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 127 "analyseur_csharp.l"
{if (debug) printf ("^= \n"); return XOREQ; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 128 "analyseur_csharp.l"
{if (debug) printf ("& \n"); return AND; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 129 "analyseur_csharp.l"
{if (debug) printf ("&= \n"); return ANDEQ; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 130 "analyseur_csharp.l"
{if (debug) printf ("~ \n"); return TILDE; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 131 "analyseur_csharp.l"
{if (debug) printf ("! \n"); return EXCL; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 132 "analyseur_csharp.l"
{if (debug) printf ("| \n"); return OR; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 133 "analyseur_csharp.l"
{if (debug) printf ("|= \n"); return OREQ; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 134 "analyseur_csharp.l"
{if (debug) printf ("< \n"); return LT; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 135 "analyseur_csharp.l"
{if (debug) printf ("> \n"); return GT; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 136 "analyseur_csharp.l"
{if (debug) printf ("<< \n"); return LTLT; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 137 "analyseur_csharp.l"
{if (debug) printf (">> \n"); return GTGT; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 138 "analyseur_csharp.l"
{if (debug) printf (">>= \n"); return GTGTEQ; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 139 "analyseur_csharp.l"
{if (debug) printf ("<<= \n"); return LTLTEQ; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 140 "analyseur_csharp.l"
{if (debug) printf ("== \n"); return EQEQ; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 141 "analyseur_csharp.l"
{if (debug) printf ("!= \n"); return NOTEQ; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 142 "analyseur_csharp.l"
{if (debug) printf ("<= \n"); return LEQ; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 143 "analyseur_csharp.l"
{if (debug) printf (">= \n"); return GEQ; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 144 "analyseur_csharp.l"
{if (debug) printf ("&& \n"); return ANDAND; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 145 "analyseur_csharp.l"
{if (debug) printf ("|| \n"); return OROR; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 146 "analyseur_csharp.l"
{if (debug) printf ("++ \n"); return PLUSPLUS; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 147 "analyseur_csharp.l"
{if (debug) printf ("-- \n"); return MINUSMINUS; }	
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 148 "analyseur_csharp.l"
{if (debug) printf ("VAR \n"); return VAR;}		
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 149 "analyseur_csharp.l"
{if (debug) printf ("EOF \n"); return END_OF_FILE;}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 150 "analyseur_csharp.l"
{if (debug) printf ("identifier \n"); set_idf_attributes(yytext, yylineno);	return IDF;}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 151 "analyseur_csharp.l"
{if (debug) printf( "ERRORLEX(%s) ", yytext );set_token_attributes(yylineno);}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 153 "analyseur_csharp.l"
ECHO;
	YY_BREAK
#line 1802 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 410 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 410 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 409);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc(new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        yyfree((yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 153 "analyseur_csharp.l"



